spring:
  datasource:
    url: jdbc:mysql://localhost:3306/happy_db?serverTimezone=GMT%2B8
    username: happytest
    password: happytest

test-config:
  hello: Hello
  world: world!
  amazing-way: Wow!

test-config2:
  hello: Hello
  world: world!
  amazing-way: Wow!

test-config3:
  hello: Hello
  world: world!
  amazing-way: Wow!