server:
  port: 12312
  servlet:
    context-path: /happyTest
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/happy_db?serverTimezone=GMT%2B8
    username: happytest
    password: happytest
mybatis-plus:
  mapperLocations: classpath:/mapper/*/*.xml
  typeAliasesPackage: com.basic.happytest.mudules.*.entity
  Configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


test-config:
  hello: Hello
  world: world!
  amazing-way: Wow!